server:
  port: 60000
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://8.141.9.87:3300/initdb_?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: ch123456!
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  http:
    encoding:
      charset: UTF-8
      force: true
  redis:
    host: 8.141.9.87
    port: 6380
    password: 123456
    database: 0

logging:
  level:
    root: INFO
    cn.mengcankeji.dd.mapper: DEBUG
    cn.mengcankeji.dd.service: DEBUG
    cn.mengcankeji.dd.web: DEBUG




dd:
  corp:
    corpId: 1
    suiteKey: 1
    suiteSecret: 1
    token: 1
    aesKey: 1
  app:
    appKey: 1
    appSecret: 1
    corpid: 1
    ssoSecret: 1